'use client'

import { MoreHorizontal, Search } from 'lucide-react'
import type { ReactNode } from 'react'
import { EmptyState } from './EmptyState'

export function DataTable<T>({ data, columns, searchPlaceholder = 'بحث...', filters, loading, emptyState, rowActions }: { data: T[]; columns: { key: string; header: string; render: (row: T) => ReactNode }[]; searchPlaceholder?: string; filters?: ReactNode; loading?: boolean; emptyState?: ReactNode; rowActions?: (row: T) => ReactNode }) {
  return <div className="flex flex-col gap-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><label className="flex items-center gap-2 rounded-lg border bg-background px-3 py-2 text-sm"><Search className="size-4 text-muted" aria-hidden="true" /><input className="min-w-0 bg-transparent outline-none" placeholder={searchPlaceholder} aria-label={searchPlaceholder} /></label>{filters && <div className="flex flex-wrap gap-2">{filters}</div>}</div><div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[640px] text-sm"><thead className="bg-chip/50"><tr>{columns.map((column) => <th key={column.key} className="px-4 py-3 text-right font-medium text-muted">{column.header}</th>)}{rowActions && <th className="px-4 py-3" aria-label="الإجراءات"><MoreHorizontal className="size-4" /></th>}</tr></thead><tbody>{loading ? Array.from({ length: 4 }).map((_, index) => <tr key={index}>{columns.map((column) => <td key={column.key} className="px-4 py-4"><div className="h-4 animate-pulse rounded bg-chip" /></td>)}</tr>) : data.map((row, index) => <tr key={index} className="border-t">{columns.map((column) => <td key={column.key} className="px-4 py-4">{column.render(row)}</td>)}{rowActions && <td className="px-4 py-4">{rowActions(row)}</td>}</tr>)}</tbody></table></div>{!loading && data.length === 0 && (emptyState ?? <EmptyState />)}<div className="flex items-center justify-between text-xs text-muted"><span>عرض {data.length} نتيجة</span><div className="flex gap-2"><button className="rounded-md border px-3 py-1.5" disabled>السابق</button><button className="rounded-md border px-3 py-1.5" disabled>التالي</button></div></div></div>
}

export default DataTable
